title: Meeting cost calculator

email: tjharrop@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Calculate the rough staffing cost of a meeting
baseurl: "/meetingcostcalculator" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: tjharrop
github_username:  tjharrop

browserTitle: NSW Meeting Calculator

stage: tool

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

remote_theme: tjharrop/NSW-jekyll-theme
